ci/cd fixed

diff --git a/.github/workflows/vm_deploy.yml b/.github/workflows/vm_deploy.yml
--- a/.github/workflows/vm_deploy.yml
+++ b/.github/workflows/vm_deploy.yml
@@ -17,7 +17,11 @@ jobs:
           password: ${{ secrets.VM_PASSWORD }}
           port: 22
           script: |
-            cd ~/AI-Powered-Integrated-Code-Analyzer-for-Efficient-Developer-WorkFlowW
+            cd ~/AI-Powered-Integrated-Code-Analyzer-for-Efficient-Developer-WorkFlow
+            if [ ! -d .git ]; then
+                echo "Error: Not a git repository. Exiting."
+                exit 1
+            fi
             git pull origin main
             cd docai
             npm install
